<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd" version="3.0" name="com.concessionaria.test.ExceptionHandlerTest" time="0.074" tests="15" errors="0" skipped="0" failures="0">
  <properties>
    <property name="java.specification.version" value="21"/>
    <property name="sun.cpu.isalist" value="amd64"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.class.path" value="C:\Users\Alberto\Documents\GitHub\OOP2724GiuntaAlberto_Exam\concessionaria\target\test-classes;C:\Users\Alberto\Documents\GitHub\OOP2724GiuntaAlberto_Exam\concessionaria\target\classes;C:\Users\Alberto\.m2\repository\junit\junit\4.13.2\junit-4.13.2.jar;C:\Users\Alberto\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;"/>
    <property name="java.vm.vendor" value="Microsoft"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="user.variant" value=""/>
    <property name="java.vendor.url" value="https://www.microsoft.com"/>
    <property name="user.timezone" value="Europe/Rome"/>
    <property name="os.name" value="Windows 11"/>
    <property name="java.vm.specification.version" value="21"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="user.country" value="IT"/>
    <property name="sun.boot.library.path" value="C:\Program Files\Microsoft\jdk-21.0.6.7-hotspot\bin"/>
    <property name="sun.java.command" value="C:\Users\Alberto\AppData\Local\Temp\surefire1292559011671931993\surefirebooter-20250628204023716_3.jar C:\Users\Alberto\AppData\Local\Temp\surefire1292559011671931993 2025-06-28T20-40-23_560-jvmRun1 surefire-20250628204023716_1tmp surefire_0-20250628204023716_2tmp"/>
    <property name="jdk.debug" value="release"/>
    <property name="surefire.test.class.path" value="C:\Users\Alberto\Documents\GitHub\OOP2724GiuntaAlberto_Exam\concessionaria\target\test-classes;C:\Users\Alberto\Documents\GitHub\OOP2724GiuntaAlberto_Exam\concessionaria\target\classes;C:\Users\Alberto\.m2\repository\junit\junit\4.13.2\junit-4.13.2.jar;C:\Users\Alberto\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="C:\Users\Alberto"/>
    <property name="user.language" value="it"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.version.date" value="2025-01-21"/>
    <property name="java.home" value="C:\Program Files\Microsoft\jdk-21.0.6.7-hotspot"/>
    <property name="file.separator" value="\"/>
    <property name="basedir" value="C:\Users\Alberto\Documents\GitHub\OOP2724GiuntaAlberto_Exam\concessionaria"/>
    <property name="java.vm.compressedOopsMode" value="Zero based"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="surefire.real.class.path" value="C:\Users\Alberto\AppData\Local\Temp\surefire1292559011671931993\surefirebooter-20250628204023716_3.jar"/>
    <property name="user.script" value=""/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="java.runtime.version" value="21.0.6+7-LTS"/>
    <property name="user.name" value="Alberto"/>
    <property name="stdout.encoding" value="Cp1252"/>
    <property name="path.separator" value=";"/>
    <property name="os.version" value="10.0"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="java.vendor.version" value="Microsoft-10800203"/>
    <property name="localRepository" value="C:\Users\Alberto\.m2\repository"/>
    <property name="java.vendor.url.bug" value="https://github.com/microsoft/openjdk/issues"/>
    <property name="java.io.tmpdir" value="C:\Users\Alberto\AppData\Local\Temp\"/>
    <property name="java.version" value="21.0.6"/>
    <property name="user.dir" value="C:\Users\Alberto\Documents\GitHub\OOP2724GiuntaAlberto_Exam\concessionaria"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="native.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Program Files\Microsoft\jdk-21.0.6.7-hotspot\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Microsoft\jdk-21.0.6.7-hotspot\bin;C:\Program Files (x86)\Common Files\Oracle\Java\java8path;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\apache-maven-3.9.10\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Users\Alberto\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Alberto\AppData\Local\GitHubDesktop\bin;C:\Users\Alberto\AppData\Roaming\npm;C://UnLockCatch/tools/vcruntime;;."/>
    <property name="java.vm.info" value="mixed mode, sharing"/>
    <property name="stderr.encoding" value="Cp1252"/>
    <property name="java.vendor" value="Microsoft"/>
    <property name="java.vm.version" value="21.0.6+7-LTS"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="65.0"/>
  </properties>
  <testcase name="testGestisciNumberFormatException" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.041">
    <system-err><![CDATA[giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler gestisciEccezione
GRAVE: Eccezione in Parsing context
java.lang.NumberFormatException: Invalid number
	at com.concessionaria.test.ExceptionHandlerTest.testGestisciNumberFormatException(ExceptionHandlerTest.java:30)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: === DETTAGLI ECCEZIONE ===
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Contesto: Parsing context
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Tipo eccezione: java.lang.NumberFormatException
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Messaggio originale: Invalid number
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Origine: com.concessionaria.test.ExceptionHandlerTest.testGestisciNumberFormatException(ExceptionHandlerTest.java:30)
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: ========================
]]></system-err>
  </testcase>
  <testcase name="testRequirePositiveConZero" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testRequireNonEmpty" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testRequireNonEmptyConStringaVuota" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testRequireNonEmptyConNull" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testGestisciConcessionariaException" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.009">
    <system-err><![CDATA[giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler gestisciEccezione
GRAVE: Eccezione in Test context
com.concessionaria.exception.ConcessionariaException: Messaggio custom
	at com.concessionaria.test.ExceptionHandlerTest.testGestisciConcessionariaException(ExceptionHandlerTest.java:22)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: === DETTAGLI ECCEZIONE ===
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Contesto: Test context
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Tipo eccezione: com.concessionaria.exception.ConcessionariaException
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Messaggio originale: Messaggio custom
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: ========================
]]></system-err>
  </testcase>
  <testcase name="testGestisciIOException" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.006">
    <system-err><![CDATA[giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler gestisciEccezione
GRAVE: Eccezione in File context
java.io.IOException: File not found
	at com.concessionaria.test.ExceptionHandlerTest.testGestisciIOException(ExceptionHandlerTest.java:38)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: === DETTAGLI ECCEZIONE ===
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Contesto: File context
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Tipo eccezione: java.io.IOException
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Messaggio originale: File not found
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Origine: com.concessionaria.test.ExceptionHandlerTest.testGestisciIOException(ExceptionHandlerTest.java:38)
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: ========================
]]></system-err>
  </testcase>
  <testcase name="testWrapException" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.002">
    <system-err><![CDATA[giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler wrapException
AVVERTENZA: Wrapping eccezione tecnica
java.lang.RuntimeException: Original message
	at com.concessionaria.test.ExceptionHandlerTest.testWrapException(ExceptionHandlerTest.java:112)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

]]></system-err>
  </testcase>
  <testcase name="testRequireInRange" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testRequireNonNull" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testRequireNonNullConNull" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testGestisciEccezioneGenerica" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.007">
    <system-err><![CDATA[giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler gestisciEccezione
GRAVE: Eccezione in Test context
java.lang.RuntimeException: Test exception
	at com.concessionaria.test.ExceptionHandlerTest.testGestisciEccezioneGenerica(ExceptionHandlerTest.java:13)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: === DETTAGLI ECCEZIONE ===
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Contesto: Test context
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Tipo eccezione: java.lang.RuntimeException
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Messaggio originale: Test exception
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: Origine: com.concessionaria.test.ExceptionHandlerTest.testGestisciEccezioneGenerica(ExceptionHandlerTest.java:13)
giu 28, 2025 8:40:24 PM com.concessionaria.exception.ExceptionHandler logContextInfo
GRAVE: ========================
]]></system-err>
  </testcase>
  <testcase name="testRequireInRangeFuoriRange" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testRequirePositiveConNegativo" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
  <testcase name="testRequirePositive" classname="com.concessionaria.test.ExceptionHandlerTest" time="0.0"/>
</testsuite>